CREATE TABLE IF NOT EXISTS player (
    id INTEGER,
    name VARCHAR(32) UNIQUE NOT NULL,
    PRIMARY KEY(id AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS leaderboard (
    id INTEGER NOT NULL,
    score INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (id) REFERENCES player(id)
);

CREATE TABLE IF NOT EXISTS weapon (
    id INTEGER,
    name VARCHAR(32) UNIQUE NOT NULL,
    damage REAL NOT NULL DEFAULT 1.0,
    speed REAL NOT NULL DEFAULT 300.0,
    idle_anim VARCHAR(64) NOT NULL,
    fire_anim VARCHAR(64) NOT NULL,
    PRIMARY KEY(id AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS enemy (
    id INTEGER,
    name VARCHAR(32) UNIQUE NOT NULL,
    damage REAL NOT NULL DEFAULT 1.0,
    speed REAL NOT NULL DEFAULT 300.0,
    behavior INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(id AUTOINCREMENT)
);