CREATE TABLE IF NOT EXISTS player (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS leaderboard (
    id INT NOT NULL,
    score INT NOT NULL DEFAULT 0,
    FOREIGN KEY (id) REFERENCES player(id)
);

CREATE TABLE IF NOT EXISTS weapon (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(32) UNIQUE NOT NULL,
    damage REAL NOT NULL DEFAULT 1.0,
    speed REAL NOT NULL DEFAULT 300.0,
    idle_anim VARCHAR(64) NOT NULL,
    fire_anim VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS enemy (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(32) UNIQUE NOT NULL,
    damage REAL NOT NULL DEFAULT 1.0,
    speed REAL NOT NULL DEFAULT 300.0,
    behavior INT NOT NULL DEFAULT 0
);